# src/email_service.py
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

GMAIL_USER = os.getenv("GMAIL_USER")
GMAIL_PASS = os.getenv("GMAIL_APP_PASS")


def _send_email(to: str, subject: str, html_body: str):
    """
    Core email sender — sirf ye function actual SMTP call karta hai.
    Baaki saare functions isko call karte hain.
    
    SMTP kya hai?
    Simple Mail Transfer Protocol — email bhejne ka standard tarika.
    Gmail ka SMTP server: smtp.gmail.com, port 465 (SSL)
    """
    msg = MIMEMultipart("alternative")
    # MIMEMultipart = email ka container
    # "alternative" = plain text + HTML dono support karega

    msg["Subject"] = subject
    msg["From"]    = GMAIL_USER
    msg["To"]      = to

    # HTML body attach karo
    msg.attach(MIMEText(html_body, "html"))

    try:
        # SSL connection banao Gmail ke saath
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_PASS)
            server.sendmail(GMAIL_USER, to, msg.as_string())
        print(f"  [Email] Sent to {to}")
        return True
    except Exception as e:
        print(f"  [Email] Failed: {e}")
        return False


def _ticket_html(ticket: dict, extra_heading: str = "") -> str:
    """
    Ticket dict se HTML email body banao.
    f-string se dynamic HTML generate ho raha hai.
    """
    steps_html = "".join(
        f"<li style='margin:4px 0'>{step}</li>"
        for step in ticket["resolution_steps"]
    )

    priority_color = {
        "P1": "#dc2626",   # red
        "P2": "#d97706",   # amber
        "P3": "#2563eb",   # blue
    }.get(ticket["priority"], "#6b7280")
    # .get(key, default) — agar key nahi mili toh default return karo

    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">

      {f'<h2 style="color:#dc2626">{extra_heading}</h2>' if extra_heading else ''}

      <h2 style="color:#1e40af">STC AutoOSS — Incident Ticket</h2>

      <div style="background:#f1f5f9; padding:16px; border-radius:8px; margin:16px 0;">
        <table style="width:100%; border-collapse:collapse;">
          <tr><td style="padding:6px; font-weight:bold; width:40%">Ticket ID</td>
              <td style="padding:6px">{ticket['ticket_id']}</td></tr>
          <tr><td style="padding:6px; font-weight:bold">Priority</td>
              <td style="padding:6px">
                <span style="background:{priority_color}; color:white;
                             padding:2px 10px; border-radius:12px; font-size:13px;">
                  {ticket['priority']}
                </span>
              </td></tr>
          <tr><td style="padding:6px; font-weight:bold">Device</td>
              <td style="padding:6px">{ticket['device']}</td></tr>
          <tr><td style="padding:6px; font-weight:bold">Region</td>
              <td style="padding:6px">{ticket['region']}</td></tr>
          <tr><td style="padding:6px; font-weight:bold">Alarm Type</td>
              <td style="padding:6px">{ticket['alarm_type']}</td></tr>
          <tr><td style="padding:6px; font-weight:bold">Description</td>
              <td style="padding:6px">{ticket['description']}</td></tr>
          <tr><td style="padding:6px; font-weight:bold">Assigned Team</td>
              <td style="padding:6px">{ticket['assigned_team']}</td></tr>
        </table>
      </div>

      <h3 style="color:#1e40af">AI Root Cause Analysis</h3>
      <div style="background:#fefce8; padding:16px; border-radius:8px; border-left:4px solid #ca8a04;">
        <p><b>Root Cause:</b> {ticket['root_cause']}</p>
        <p><b>Confidence:</b> {ticket['confidence'].upper()}</p>
        <p><b>Estimated Fix Time:</b> {ticket['estimated_fix_time']}</p>
      </div>

      <h3 style="color:#1e40af">Resolution Steps</h3>
      <ol style="background:#f0fdf4; padding:16px 16px 16px 32px;
                 border-radius:8px; border-left:4px solid #16a34a;">
        {steps_html}
      </ol>

      <p style="color:#6b7280; font-size:12px; margin-top:24px;">
        Generated by STC AutoOSS AI — {ticket['created_at']}
      </p>
    </div>
    """


def send_new_ticket_email(ticket: dict):
    """L1 team ko naya ticket aane pe email bhejo."""
    l1_email = os.getenv("L1_EMAIL")
    subject  = f"[{ticket['priority']}] New Incident: {ticket['alarm_type']} on {ticket['device']}"
    body     = _ticket_html(ticket)
    return _send_email(l1_email, subject, body)


def send_escalation_email(ticket: dict):
    """L3 team ko escalation email bhejo."""
    l3_email = os.getenv("L3_EMAIL")
    subject  = f"[ESCALATED][{ticket['priority']}] Unresolved: {ticket['alarm_type']} on {ticket['device']}"
    body     = _ticket_html(ticket, extra_heading="ESCALATED — Not resolved in time!")
    return _send_email(l3_email, subject, body)


# ── Test karo ──────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    dummy_ticket = {
        "ticket_id":         "INC-TEST-001",
        "priority":          "P1",
        "device":            "CoreRouter-Riyadh-02",
        "region":            "Riyadh",
        "alarm_type":        "BGP_DOWN",
        "description":       "BGP session dropped with peer 10.45.2.1",
        "assigned_team":     "NOC-L2",
        "root_cause":        "Physical link failure between routers",
        "confidence":        "high",
        "estimated_fix_time": "20 minutes",
        "resolution_steps":  ["Step 1: Check link", "Step 2: Replace cable"],
        "escalate_to_l3":    False,
        "created_at":        "2026-04-15T09:30:00"
    }
    send_new_ticket_email(dummy_ticket)
    print("Check your email!")